[project]
name = "us-flag-status"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
]
